# -*- coding: utf-8 -*-
"""clima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYcGiL7PMnpcmlnOdAoBb2Y_KwFaEWJS
"""

# ==============================================================================
# SCRIPT MAESTRO: main.py (Versión Producción para GitHub Actions)
# ==============================================================================
import openmeteo_requests
import requests_cache
import pandas as pd
from retry_requests import retry
from datetime import datetime
import pytz

# --- CONFIGURACIÓN (Variables Globales) ---
COORDENADAS_MONITOREO = {
    'lat': 7.1193,  # Ejemplo: Zona crítica en Santander
    'lon': -73.1227
}
SUSCEPTIBILIDAD_ESTATICA = 0.90 # Este valor vendrá de tu mapa GEE en el futuro

# --- MÓDULO 1: INGESTA ---
def obtener_datos():
    # Configuración de Cliente
    cache_session = requests_cache.CachedSession('.cache', expire_after=3600)
    retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
    openmeteo = openmeteo_requests.Client(session=retry_session)

    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": COORDENADAS_MONITOREO['lat'],
        "longitude": COORDENADAS_MONITOREO['lon'],
        "hourly": ["precipitation", "soil_moisture_0_to_1cm", "soil_moisture_1_to_3cm"],
        "timezone": "auto",
        "past_days": 3,
        "forecast_days": 1
    }

    responses = openmeteo.weather_api(url, params=params)
    response = responses[0]

    # Procesamiento
    hourly = response.Hourly()
    data = {
        "date": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left"
        ),
        "lluvia_mm": hourly.Variables(0).ValuesAsNumpy(),
        "humedad_suelo": hourly.Variables(1).ValuesAsNumpy()
    }

    df = pd.DataFrame(data)
    df['date'] = df['date'].dt.tz_convert('America/Bogota')
    return df

# --- MÓDULO 2: LÓGICA HIDROLÓGICA ---
def procesar_amenaza(df):
    df.set_index('date', inplace=True)

    # Acumulado 3 días
    df['lluvia_3d'] = df['lluvia_mm'].rolling(window='72h').sum()

    # Semáforo Climático (0-3)
    def semaforo_clima(fila):
        if (fila['lluvia_3d'] > 60) or (fila['humedad_suelo'] > 0.4 and fila['lluvia_3d'] > 20):
            return 3 # Roja Climática
        elif fila['lluvia_3d'] > 40:
            return 2 # Naranja Climática
        elif fila['lluvia_3d'] > 15:
            return 1 # Amarilla Climática
        return 0 # Verde

    df['alerta_clima'] = df.apply(semaforo_clima, axis=1)
    return df

# --- MÓDULO 3: MATRIZ DE DECISIÓN ---
def evaluar_riesgo_total(df, susc_mapa):
    ultimo_dato = df.iloc[-1] # Solo nos importa la última hora (tiempo real)

    amenaza = ultimo_dato['alerta_clima']
    lluvia_3d = ultimo_dato['lluvia_3d']

    # Matriz Susceptibilidad vs Amenaza
    nivel_final = 0
    mensaje = "Condiciones Normales"

    if susc_mapa > 0.8: # Zona Crítica
        if amenaza >= 2:
            nivel_final = 3
            mensaje = "🚨 ALARMA ROJA: Evacuación Inmediata (Suelo Crítico + Lluvia Intensa)"
        elif amenaza == 1:
            nivel_final = 2
            mensaje = "🟠 ALERTA NARANJA: Preparar respuesta (Suelo Crítico + Lluvia Moderada)"
        elif amenaza == 0 and lluvia_3d > 5:
            nivel_final = 1
            mensaje = "🟡 ALERTA AMARILLA: Monitoreo activado (Suelo Crítico + Lluvia Leve)"

    elif susc_mapa < 0.4: # Zona Estable
        if amenaza == 3:
            nivel_final = 2
            mensaje = "🟠 ALERTA NARANJA: Riesgo por evento extremo en zona estable"

    else: # Zona Media
        nivel_final = amenaza
        if nivel_final > 0: mensaje = f"Alerta Nivel {nivel_final} por condiciones climáticas"

    return nivel_final, mensaje, ultimo_dato

# --- MÓDULO 4: SISTEMA DE NOTIFICACIÓN (Simulado) ---
def enviar_notificacion(nivel, mensaje, datos):
    """
    Aquí es donde conectaremos el email real en la próxima fase.
    Por ahora, imprimimos el 'log' del sistema.
    """
    print("\n" + "="*50)
    print(f"📡 REPORTE GEOALERTA - {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("="*50)
    print(f"📍 Coordenadas: {COORDENADAS_MONITOREO}")
    print(f"⛰️ Susceptibilidad Mapa: {SUSCEPTIBILIDAD_ESTATICA}")
    print("-" * 20)
    print(f"💧 Lluvia 3 Días: {datos['lluvia_3d']:.1f} mm")
    print(f"🌱 Humedad Suelo: {datos['humedad_suelo']:.2f} m3/m3")
    print("-" * 20)
    print(f"🚦 NIVEL DE ALERTA: {nivel}")
    print(f"📝 MENSAJE: {mensaje}")
    print("="*50 + "\n")

# --- EJECUCIÓN MAESTRA ---
if __name__ == "__main__":
    print("🔄 Iniciando ejecución automática...")
    try:
        # 1. Ingesta
        df_raw = obtener_datos()
        # 2. Proceso
        df_proc = procesar_amenaza(df_raw)
        # 3. Decisión
        nivel, msg, data_now = evaluar_riesgo_total(df_proc, SUSCEPTIBILIDAD_ESTATICA)
        # 4. Acción
        if nivel > 0:
            enviar_notificacion(nivel, msg, data_now)
        else:
            print("✅ Sistema Operativo. Sin alertas activas.")

    except Exception as e:
        print(f"❌ Error crítico en el sistema: {e}")